### ISSUE TITLE
how can you disable default crosshair 

### ISSUE THREAD

**Issue by celian-hamon** [Strykus/CustCross#2]
![image](https://user-images.githubusercontent.com/61624140/168549738-a739af72-5fa2-45ee-a656-e79977369e31.png)
![image](https://user-images.githubusercontent.com/61624140/168549759-e128105f-2d3d-4cc3-b274-a11a2fcd8881.png)
i have the default corsshair that get on top of the custom one

**Comment by Strykus** [comment]
Change `"LoadPriority"` from `2` to `1` in `mod.json`
One person already have that problem. That appear when it conflict with other mods

**Comment by celian-hamon** [comment]
okay will try thanks

**Comment by Strykus** [comment]
I changed LoadPriority in Download files

**Comment by celian-hamon** [comment]
yup the load order fix the crosshair problem 👍
